[pytest]
addopts = --alluredir=allure-results -sv --browser=chrome --env=dev
markers =
    smoke: smoke tests
    regression: regression tests
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*